# main text of home
name: Stefan Walz
bio: Financial Economics

# twitter summary info
description: About Me

picture: assets/images/linkedin_pic.jpg

url: http://sgwalz.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
email: stefan.walz@columbia.edu

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
